### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by EriniKarpadaki** [foridpathan/Codeigniter-Ajax-Admin-Theme-with-dynamic-menu#1]
Hi.
Below is what I did.
1. Download and unzip all files.
2. Create a database and import cl_ajax.sql.zip file
3. Set database config in Config/Database.php
4. Run this application using your localhost (xampp)
5. Create and configure .htaccess file to remove index.php

When I tried to visit the site on localhost, it gave me redirect too many times error.
So, I fixed it by removing  `$this->checkLoggedIn();` in Users/login function.

After that, I tried to login on login page, it gave me 500 internal server error.
![image](https://user-images.githubusercontent.com/69481913/93570708-fc994c80-f9c5-11ea-901c-ba4c7f5a06ae.png)
![image](https://user-images.githubusercontent.com/69481913/93570734-0a4ed200-f9c6-11ea-8bfa-d4d5c16e6c4b.png)

Any idea why?

Thanks in advance :)

**Comment by foridpathan** [comment]
Thanks for your message.

Please restore $this->checkLoggedIn(); don't neet to delete this function.

### Here is your solution
**copy and paste this code** 
inside root folder
[`.htaccess code`](https://raw.githubusercontent.com/foridpathan/Codeigniter-Ajax-Admin-Theme-with-dynamic-menu/master/.htaccess)

also
inside public folder
[`.htaccess code`](https://raw.githubusercontent.com/foridpathan/Codeigniter-Ajax-Admin-Theme-with-dynamic-menu/master/public/.htaccess)

overright that files:
**public/.htaccess also overrght root folder .htaccess file**

If there any problem let me know
Thanks

**Comment by EriniKarpadaki** [comment]
Thanks for your quick solutions.
I already fixed it :)
It was a database connection error.
It doesn't display error from Model side.

Thanks again.

**Comment by foridpathan** [comment]
oh I see it's okay heppy coding 👍
